### ISSUE TITLE
How can I destroy the timer after it's been called?

### ISSUE THREAD

**Issue by felixchan** [Krb686/nanotimer#10]
Hi,

Is there a way to destroy the timer after it's been called?   We'll be creating many instances of the timer every minute and don't want any memory problems.

Thanks!

```
var timer = new NanoTimer();
timer.setTimeout(function(id){
     timer.clearInterval();
     //destroy timer?
 }, [id], '60s');
```

**Comment by Krb686** [comment]
There really is no way to "delete" a variable in javascript.  Garbage collection is handled by the browser (or in the case of node.js, I presume would be the V8 engine).  The keyword "delete' in javascript only removes a property from an object.  Thus if you declare a variable implicity without the var keyword, it will be a property of the global object and can be deleted.  If you don't though, and you declare your variable with var, that won't be the case.  I have read in several places that setting a variable to null or undefined may speed up the garbage collection process, but I really don't know.  This is not a nanotimer specific issue though, so I'm closing this.  Have a look through stackoverflow for things like this, such as here: http://stackoverflow.com/questions/16963066/javascript-how-to-delete-a-variable
