### ISSUE TITLE
process.hrtime() only accepts an Array tuple.

### ISSUE THREAD

**Issue by kenzik** [Krb686/nanotimer#16]
Hello, I'm getting the following error when using nanotimer:

```
/var/node_server/node_modules/nanotimer/lib/nanoTimer.js:375
                var difArray = process.hrtime(this.timeOutT1);
                                       ^

TypeError: process.hrtime() only accepts an Array tuple.
    at TypeError (native)
    at NanoTimer.clearTimeout (/var/node_server/node_modules/nanotimer/lib/nanoTimer.js:375:26)
    at eval (eval at <anonymous> (eval at <anonymous> (/var/node_server/run.js:1:0)), <anonymous>:276:16)
    at NanoTimer.setTimeout (/var/node_server/node_modules/nanotimer/lib/nanoTimer.js:339:4)
    at null.<anonymous> (/var/node_server/node_modules/nanotimer/lib/nanoTimer.js:319:63)
    at Timer.listOnTimeout (timers.js:92:15)

```

What could be the cause of this?

**Comment by Krb686** [comment]
Hi, can you please post your code or a snippet in which in shows this error?

**Comment by kenzik** [comment]
```
timerA.setTimeout(function(){
        gamesHolder[gameId].closed = true;
        timerA.clearTimeout();
        timerB.setTimeout(function(){
            updateGameState();
            timerB.clearTimeout();
            timerC.setTimeout(function(){
                timerC.clearTimeout();
                drawWinner(gameId);
            }, '', '500m');
        }, '', '1s');
    }, '', '35s');
```

I removed the clearTimeout() calls for now and it seems to be working fine now, not sure what happened earlier.

**Comment by Krb686** [comment]
Ok thanks.  And in your stack trace  where it says:

    at NanoTimer.setTimeout (/var/node_server/node_modules/nanotimer/lib/nanoTimer.js:339:4)

Which line is that in the snipped you posted?

**Comment by kenzik** [comment]
Hello, it is the first setTimeout (timerA) that failed.

**Comment by Krb686** [comment]
I ran this:

    var NanoTimer = require('../lib/nanoTimer.js');

    var timerA = new NanoTimer();
    var timerB = new NanoTimer();
    var timerC = new NanoTimer();

    timerA.setTimeout(function(){
        console.log("Timer A trigger!");
        //gamesHolder[gameId].closed = true;
        timerA.clearTimeout();
        timerB.setTimeout(function(){
            console.log("Timer B trigger!");
            //updateGameState();
            timerB.clearTimeout();
            timerC.setTimeout(function(){
                console.log("Timer C trigger!");
                timerC.clearTimeout();
                //drawWinner(gameId);
            }, '', '500m');
        }, '', '1s');
    }, '', '5s');


And got this:


![nanotimer_error_2](https://cloud.githubusercontent.com/assets/959619/10706779/21add57e-79b8-11e5-971c-a1ee5cc9cb6c.png)

**Comment by Krb686** [comment]
Kenzik, I didn't fully catch what was going on here until Imommaerts brought my attention to it.  The timer's clearTimeout function is really meant to stop a timeout before it happens.  In your case, you are calling clearTimeout as a result of the timeout triggering, so I would say you really don't need those clearTimeout calls in your code.  If you are calling clearTimeout as a means of cleaning up then I would say ideally when the timeout triggers everything should get cleaned up internally.  I attempted to make this happen but I may have missed a few things, so I'll be double checking that.
