### ISSUE TITLE
0.3.11 on Ubuntu isn't loading

### ISSUE THREAD

**Issue by rob-gordon** [Krb686/nanotimer#18]
I use nanotimer in a project I built when 0.3.10 was the current version. I moved the project over to Ubuntu 14 (where I had run it before with no problems) and node kept saying it couldn't find nanotimer. I tried installing as root and installing globally but to no avail. It began to work again after I installed 0.3.10. I don't know if this is exclusive to my computer, but I thought I would post it here in case.

    rob@le-ciel:~/Dev/test$ npm install nanotimer
    npm http GET https://registry.npmjs.org/nanotimer
    npm http 304 https://registry.npmjs.org/nanotimer
    nanotimer@0.3.11 node_modules/nanotimer
    rob@le-ciel:~/Dev/test$ node
    > var Nanotimer = require('nanotimer')
    Error: Cannot find module 'nanotimer'
        at Function.Module._resolveFilename (module.js:338:15)
        at Function.Module._load (module.js:280:25)
        at Module.require (module.js:364:17)
        at require (module.js:380:17)
        at repl:1:17
        at REPLServer.self.eval (repl.js:110:21)
        at repl.js:249:20
        at REPLServer.self.eval (repl.js:122:7)
        at Interface.<anonymous> (repl.js:239:12)
        at Interface.EventEmitter.emit (events.js:95:17)
    > 
    (^C again to quit)
    > 
    rob@le-ciel:~/Dev/test$ sudo rm -rf node_modules/
    rob@le-ciel:~/Dev/test$ npm install nanotimer@0.3.10
    npm http GET https://registry.npmjs.org/nanotimer/0.3.10
    npm http 304 https://registry.npmjs.org/nanotimer/0.3.10
    nanotimer@0.3.10 node_modules/nanotimer
    rob@le-ciel:~/Dev/test$ node
    > var Nanotimer = require('nanotimer')
    undefined
    > var timerA = new Nanotimer()
    undefined

**Comment by BruceHubbard** [comment]
We just submitted the pull request: https://github.com/Krb686/nanotimer/pull/19

**Comment by Krb686** [comment]
Fixed by https://github.com/Krb686/nanotimer/pull/19

**Comment by BruceHubbard** [comment]
Thanks @Krb686!
