### ISSUE TITLE
First few intervals are way off

### ISSUE THREAD

**Issue by ImmanuelSamuel** [Krb686/nanotimer#6]
Code:

var task = function() {
    var date = new Date();
    console.log(date.getMilliseconds());
}

var NanoTimer = require('nanotimer');
var timerA = new NanoTimer();
timerA.setInterval(task, '', '4m', function(err) {
    if(err) {
        //error
    }
});

Intervals should be 4 milliseconds.

Output:

Milliseconds
492
502
504
504
508
513
516
520
524
528
532

**Comment by Krb686** [comment]
So a couple of things come to mind here.  Unfortunately, a lot of times I believe the accuracy available to you (within a certain range) is very dependent on your specific system, what else is running, and other things.  That's essentially true for all code though, but especially javascript.  In fact when I run your exact code you have pasted, I get even worse results than you.  

I have one idea that may mitigate this, but I'm not sure at this point how far I can take it.  That idea is that currently the way setInterval is coded, it does error checking and some setup code at the top of the function that gets repeated every interval.  This could probably be condensed and really only needs to be checked at the first call of every unique set of intervals.  This would reduce the overhead and probably improve the accuracy a bit.  Beyond that I'm not sure what else could be done.  

In your case, your worst error is the 2nd interval which is 6ms off (from expected 496), then 4ms off (from 500).  After that though, it looks like you get fairly good results.  Another thing to take into account is how long does it actually take to acquire a new date every interval? And does your javascript application require such a high level of accuracy? What are you using the timer for?

**Comment by Krb686** [comment]
It does strike me as odd that the accuracy is off by such a relatively large amount (in the ms range) when the timer uses setImmediate for intervals smaller than 25 milliseconds.  I suspect that date.getMilliseconds inherent inaccuracy may have something to do with this.

**Comment by Krb686** [comment]
Here is a small test function I wrote very similar to yours, with the exception of instead of using `date.getMilliseconds` as the time reference, it uses the same `process.hrtime` that the timer is built upon.  

Here are the results.

![nanotimer_4ms_error](https://cloud.githubusercontent.com/assets/959619/5623544/d5c9987e-9523-11e4-8daf-b7a14a0442c6.png)


Excluding the first few datapoints, I would say that is an amazingly small error.  Accurate to even the 2nd decimal place (which is ~10ns range) for almost every data point.

**Comment by Krb686** [comment]
Closing this as it does not appear to be a real bug/issue.  Please comment if you have further questions
