### ISSUE TITLE
io.js compat

### ISSUE THREAD

**Issue by vohof** [Krb686/nanotimer#8]
```
$ node -v
v1.0.3
````

Would result to `Error: Please update to the latest version of node!`.

**Comment by Krb686** [comment]
You are correct! That has been fixed, thanks.  Though I am curious that you are just pointing out the potential flaw and don't actually have a version of node identifying itself as v1.0.3?

**Comment by vohof** [comment]
I have :) I am using [io.js](https://iojs.org) :sparkles:

**Comment by Krb686** [comment]
Very cool! Let me know if you have any further issues with nanotimer. Hope you are getting good use out of it
